config/routes.rb
MathIsBasic::Application.routes.draw do
  root :to => "home#index"
  authenticated :user do
    root :to => 'user#index'
  end
  devise_for :users, :controllers => { :registrations => "users" }
  resources :users
  resources :admin_pages, :only => [:index]
  resources :subjects, :except => :show 
  resources :lessons
  resources :lesson_templates, :except => :show
  match "/home/solve" => "home#solve"

end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController

  def index
  	@title = 'Home'
    @subjects = Subject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end


end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/views/admin_pages/index.html.erb
<div class="center hero-unit">
<h2>Application Adminstration</h2>
<table class="table table-bordered table-condensed">
  <tr>
    <th>Name</th>
    <th>Maxlessonlevel</th>
    <th>Minlessonlevel</th>
    <th></th>
    <th></th>
  </tr>
  <% @subjects.each do |subject| %>
  <tr>
    <td><%= subject.name %></td>
    <td><%= subject.maxLessonLevel %></td>
    <td><%= subject.minLessonLevel %></td>
    <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
    <td><%= button_to 'Delete', subject_path(subject), :method => :delete, :confirm => 'Are you Sure?', 
        :title => 'Delete', :class => 'btn btn-small btn-warning :active' %></td>
  </tr>
  <% end %>
</table>
<br />
<%= link_to 'New Subject', new_subject_path, class: "btn btn-small btn-primary"  %>
</div>