config/routes.rb
MathIsBasic::Application.routes.draw do
  root :to => "home#index"
  authenticated :user do
    root :to => 'user#index'
  end
  devise_for :users, :controllers => { :registrations => "users" }
  resources :users
  resources :admin_pages, :only => [:index]
  resources :subjects, :except => :show 
  resources :lessons
  resources :lesson_templates, :except => :show
  match "/home/solve" => "home#solve"

end

app/models/subject.rb
class Subject
  include Mongoid::Document
  field :name, type: String
  field :maxLessonLevel, type: Integer, :default => 0
  field :minLessonLevel, type: Integer, :default => 0
  validates_uniqueness_of :name
  validates_presence_of :name
  embeds_many :lessons, :cascade_callbacks=> true
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def new
    @subject = Subject.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def create
    @subject = Subject.new(params[:subject])
    @subject.save
    render 'new'
  end

  def update
    @subject = Subject.find(params[:id])
    @subject.update_attributes(params[:subject])
    render 'edit'
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to admin_pages_path }
      format.json { head :no_content }
    end
  end


end

app/views/subjects/_error_messages.html.erb
<% if @subject.errors.any? %>
	<div id="error_explanation">
	  	<div class="alert alert-error">
	    	The form contains <%= pluralize(@subject.errors.count, "error") %>.
	    </div>
		<ul>
			<% @subject.errors.full_messages.each do |msg| %>
		  		<li>*<%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/subjects/_fields.html.erb
<%= render 'error_messages' %>
<%= f.label :name %><%= f.text_field :name %><br />
<%= f.label :minLessonLevel, "Minimum Lesson Level" %><%= f.number_field :minLessonLevel %><br/>    
<%= f.label :maxLessonLevel, "Maximum Lesson Level" %><%= f.number_field :maxLessonLevel %><br />

app/views/subjects/edit.html.erb
<div class="row">
	<p align="right">	
		<h2>Edit Subject</h2>
	</p>
	<div class="span8">
	    <%= form_for @subject, :url => {:action => "update"} do |f| %>
	      <%= render 'fields', f: f %>
	      <%= f.submit "Submit", class: "btn btn-small btn-primary" %>
	    <% end %>
	</div>
</div>

<% if @subject.lessons.size > 0 %>
	<br /><br />
	<div class="row">	
		<div class="span8">
			<table class="table table-striped table-bordered table-condensed">
			  <caption><i><%=@subject.name%>'s Lessons</i></caption>
			  <thead>
			  <tr>
			    <th>Name</th>
			    <th>Level</th>
			    <th>Minimum Template Level</th>
			    <th>Maximum Template Level</th>
			    <th/><th/>
			  	</tr>
			  </thead>	
				<% @subject.lessons.each do |lesson| %>
				  <tr>
				    <td><%= lesson.name %></td>
				    <td><%= lesson.level %></td>
				    <td><%= lesson.minLessonTemplateLevel %></td>
				    <td><%= lesson.maxLessonTemplateLevel %></td>
				    <td><%= link_to 'Edit', edit_lesson_path(lesson, :subject_id => @subject.id)  %></td>
				    <td><%= button_to 'Delete', lesson_path(lesson, :subject_id => @subject.id), :method => :delete, 
				    	:confirm => 'Are you Sure?', :title => 'Delete',:class => 'btn btn-small btn-warning :active' %></td>
				  </tr>
				<% end %>
			</table>
		</div>
	</div>	
<%end%>

<div class="row">
	<div class="span8">
	<%= link_to 'New Lesson', new_lesson_path(:subject_id => @subject.id), class: "btn btn-small btn-primary"  %>
	<br/><br/><br/><br/>
	<%= link_to 'Back to Admin Home', admin_pages_path %>
	</div>
</div>

app/views/subjects/new.html.erb
<div class="row">
<h2>New subject</h2>
	<div class="span8">
    <%= form_for @subject, :url => {:action => "create"} do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create Subject", class: "btn btn-small btn-primary" %>
    <% end %>
    <br/>
	<%= link_to 'Back to Admin Home', admin_pages_path %>    
	</div>
</div>    