config/routes.rb
MathIsBasic::Application.routes.draw do
  root :to => "home#index"
  authenticated :user do
    root :to => 'user#index'
  end
  devise_for :users, :controllers => { :registrations => "users" }
  resources :users
  resources :admin_pages, :only => [:index]
  resources :subjects, :except => :show 
  resources :lessons
  resources :lesson_templates, :except => :show
  match "/home/solve" => "home#solve"

end

app/models/lesson.rb
class Lesson
  include Mongoid::Document
  field :name, type: String
  field :level, type: Integer
  field :maxLessonTemplateLevel, type: Integer, :default => 0
  field :minLessonTemplateLevel, type: Integer, :default => 0
  embedded_in :subject,:inverse_of => :subjects
  embeds_many :lesson_templates, :cascade_callbacks=> true
  validates_uniqueness_of :name
  validates_presence_of :name
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def new
    subject = Subject.find(params[:subject_id])  
 	  @lesson = Lesson.new
    @lesson.subject = subject
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lesson }
    end  	
  end

  def edit
    subject = Subject.find(params[:subject_id])
    @lesson = subject.lessons.find(params[:id])
  end

  def create
    subject= Subject.find(params[:subject_id])
    @lesson = subject.lessons.create!(params[:lesson])
    @lesson.save
    render 'new'
  end

  def update
    subject = Subject.find(params[:subject_id])
    @lesson = subject.lessons.find(params[:id])
    @lesson.update_attributes(params[:lesson])
    render 'edit'
  end


  def destroy
    @subject= Subject.find(params[:subject_id])
    @lesson = @subject.lessons.find(params[:id])
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to edit_subject_path(@subject) }
      format.json { head :no_content }
    end

  end
  
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_error_messages.html.erb
<% if @lesson.errors.any? %>
	<div id="error_explanation">
	  	<div class="alert alert-error">
	    	The form contains <%= pluralize(@lesson.errors.count, "error") %>.
	    </div>
	    <ul>
		 	<% @lesson.errors.full_messages.each do |msg| %>
	  			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/lessons/_fields.html.erb
<%= render 'error_messages' %>
<%= f.label :name %> <%= f.text_field :name %> <br/>
<%= f.label :level %> <%= f.number_field :level %> <br/>
<%= f.label :minLessonTemplateLevel, "Minimum Template Level" %><%= f.number_field :minLessonTemplateLevel %><br/>
<%= f.label :maxLessonTemplateLevel, "Maximum Template Level" %><%= f.number_field :maxLessonTemplateLevel %><br />

app/views/lessons/edit.html.erb
<div class="row">
	<p align="right">
		<h2>Editing Lesson</h2>
	</p>
  	<div class="span8">
	    <%= form_for @lesson, :url => {:subject_id => @lesson.subject.id, :action => "update"} do |f| %>
	      <%= render 'fields', f: f %>
	      <%= f.submit "Submit", class: "btn btn-small btn-primary" %>
	    <% end %>
  	</div>
</div>

<% if @lesson.lesson_templates.size > 0 %>
	<br /><br />
	<div class="row">	
		<div class="span8">
			<table class="table table-striped table-bordered table-condensed">
				<caption><i><%=@lesson.name%>'s Templates</i></caption>
			 	<thead>
		  		<tr>
		    		<th>Name</th>
		    		<th>Template Level</th>
		    		<th></th>
		    		<th></th>
		  		</tr>
		  		</thead>
				<% @lesson.lesson_templates.each do |lesson_template| %>
	  			<tr>
				    <td><%= lesson_template.name %></td>
				    <td><%= lesson_template.templateLevel %></td>
				    <td><%= link_to 'Edit', edit_lesson_template_path(lesson_template, :lesson_id => lesson_template.lesson, :subject_id => lesson_template.lesson.subject) %></td>
				    <td><%= button_to 'Delete', lesson_template_path(lesson_template, :lesson_id => @lesson.id, 
				    	:subject_id => @lesson.subject.id), :method => :delete, 
	    				:confirm => 'Are you Sure?', :title => 'Delete',:class => 'btn btn-small btn-warning :active' %></td>
	  			</tr>
				<% end %>
			</table>
		</div>
	</div>	
<%end%>

<div class="row">
	<div class="span8">
		<%= link_to 'New Template', new_lesson_template_path(:lesson_id => @lesson, :subject_id => @lesson.subject), class: "btn btn-small btn-primary"  %>
		<br /><br /><br /><br />
		<%= link_to "Back to #{@lesson.subject.name}", edit_subject_path(@lesson.subject) %>
	</div>
</div>	

app/views/lessons/new.html.erb
<div class="row">
	<h2>New Lesson</h2>
	<div class="span8">
	    <%= form_for @lesson, :url => {:subject_id => @lesson.subject.id, :action => "create"} do |f| %>
	      <%= render 'fields', f: f %>
	      <%= f.submit "Create Lesson", class: "btn btn-small btn-primary" %>
	    <% end %>
	<br/>
    <%= link_to "Back to #{@lesson.subject.name}", edit_subject_path(@lesson.subject) %>
  </div>
</div>