config/routes.rb
MathIsBasic::Application.routes.draw do
  root :to => "home#index"
  authenticated :user do
    root :to => 'user#index'
  end
  devise_for :users, :controllers => { :registrations => "users" }
  resources :users
  resources :admin_pages, :only => [:index]
  resources :subjects, :except => :show 
  resources :lessons
  resources :lesson_templates, :except => :show
  match "/home/solve" => "home#solve"

end

app/views/layouts/_footer.html.erb
<footer id="page_footer">
<ul>
      <li><%= link_to "Admin Pages",   admin_pages_path %></li>
      <li><%= link_to "Contact", '#' %></li>
</ul>
<p>&copy; 2013 PSA. All Rights Reserved</p>
</footer>

app/views/layouts/_header.html.erb
  <header id="page_header" role="banner">
    <nav id="utility">
      <p>
        <% if user_signed_in? %>
              You are logged in as <strong><%= user.name%></strong>
              <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %> | 
              <%= link_to('Edit account', edit_user_registration_path) %>
        <% else %>
              <%= link_to('Login', new_user_session_path)  %>
              <%= link_to('Sign up', new_user_registration_path)  %>
        <% end %>
      </p>  
    </nav>     
      <%= link_to(
        image_tag("logo.png",
        alt: "Artflow",
        id: "logo"),
        root_path,
        title: "Dashboard") 
      %>         
</header>

app/views/layouts/_main_nav.html.erb
<% content_for :main_navigation do %>	
	<nav id="main_nav" role="navigation">
       <ul>
       <li><%= nav_tab 'Home', root_path, current: current_tab %></li>
       <li><%= nav_tab 'Creations', root_path, current: current_tab %></li>
       <li><%= nav_tab 'Campaigns', root_path, current: current_tab %></li>
       <li><%= nav_tab 'Projects', root_path, current: current_tab %></li>
       <li><%= nav_tab 'Designers', root_path, current: current_tab %></li>
       </ul>
    </nav>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Mathflow</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    
    <div class="container">
      <% if notice %>
        <p class="notification notice">
          <%= notice %>
        </p>
      <% end %>
      <% if alert %>
        <p class="notification alert">
          <%= alert %>
        </p>
      <% end %>
      <section id="content">
        <%= yield %>
      </section>
    </div>
  <%= render 'layouts/footer' %>
  </body>
</html>